'use strict';
const D=window.STATS_DATA,$=s=>document.querySelector(s),NS='http://www.w3.org/2000/svg';
let mode='knowledge',scope=D.knowledge[0].domain,zoom=1,current=null,selected=null;
const allTerms=[...new Set([...D.knowledge,...D.decision].flatMap(r=>r.terms))];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rows(){return D[mode==='decision'?'decision':'knowledge']}
function graphData(rs,title){const nodes=[{id:'root',label:title,level:0}],edges=[],seen=new Set(['root']);function add(id,label,level){if(!seen.has(id)){seen.add(id);nodes.push({id,label,level})}}function edge(a,b){if(!edges.some(e=>e[0]===a&&e[1]===b))edges.push([a,b])}for(const r of rs){const d='d:'+r.domain,g='g:'+r.domain+'|'+r.group;add(d,r.domain,1);add(g,r.group,2);edge('root',d);edge(d,g);for(const t of r.terms){const id='t:'+t;add(id,t,3);edge(g,id)}}return{nodes,edges}}
function categories(){const domains=[...new Set(rows().map(r=>r.domain))];$('#categories').innerHTML='';for(const d of ['全部',...domains]){let b=document.createElement('button');b.textContent=d;b.className=d===scope?'active':'';b.onclick=()=>{scope=d;$('#depth').value=d==='全部'?'1':'3';categories();render()};$('#categories').append(b)}}
function svgEl(tag,attrs={},parent=$('#graph')){let el=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);parent.append(el);return el}
function wrap(s,max=29){const lines=[];let line='',size=0;for(const c of s){let w=c.charCodeAt(0)>255?1.8:1;if(size+w>max){lines.push(line);line='';size=0}line+=c;size+=w}if(line)lines.push(line);return lines}
function render(){if(mode==='catalog'){catalog();return}if(mode==='about')return;const title=mode==='decision'?'方法選用 Method selection':'Statistics 統計學';const rs=scope==='全部'?rows():rows().filter(r=>r.domain===scope);current=graphData(rs,title);const depth=Number($('#depth').value);const nodes=current.nodes.filter(n=>n.level<=depth),ids=new Set(nodes.map(n=>n.id));const edges=current.edges.filter(e=>e.every(id=>ids.has(id)));let heights=[];for(let i=0;i<=depth;i++){let y=30;for(const n of nodes.filter(n=>n.level===i)){n.lines=wrap(n.label);n.h=Math.max(58,n.lines.length*17+24);n.x=25+i*315;n.y=y;y+=n.h+20}heights.push(y)}const H=Math.max(350,...heights),W=depth*315+315;for(let i=0;i<=depth;i++)for(const n of nodes.filter(n=>n.level===i))n.y+=(H-heights[i])/2;current.W=W;current.H=H;const svg=$('#graph');svg.innerHTML='';svg.setAttribute('viewBox',`0 0 ${W} ${H}`);const defs=svgEl('defs'),m=svgEl('marker',{id:'arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:6,markerHeight:6,orient:'auto'},defs);svgEl('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'#a1b9af'},m);const map=new Map(nodes.map(n=>[n.id,n]));for(const[a,b]of edges){const x=map.get(a),y=map.get(b),sx=x.x+270,sy=x.y+x.h/2,tx=y.x,ty=y.y+y.h/2;svgEl('path',{d:`M${sx},${sy} C${sx+23},${sy} ${tx-23},${ty} ${tx},${ty}`,fill:'none',stroke:'#afc5ba','stroke-width':1.2,'marker-end':'url(#arrow)'})}for(const n of nodes){const g=svgEl('g',{class:'node',tabindex:0,role:'button','aria-label':n.label,'data-id':n.id});svgEl('title',{},g).textContent=n.label;const colors=['#173d40','#dfede2','#f1f5eb','#ffffff'];svgEl('rect',{x:n.x,y:n.y,width:270,height:n.h,rx:9,fill:colors[n.level],stroke:selected===n.id?'#cf953a':'#b8cdc1','stroke-width':selected===n.id?3:1},g);const t=svgEl('text',{x:n.x+14,y:n.y+23,fill:n.level===0?'white':'#183d3d','font-size':12,'font-family':'system-ui, sans-serif'},g);n.lines.forEach((s,i)=>svgEl('tspan',{x:n.x+14,dy:i?17:0},t).textContent=s);g.addEventListener('click',()=>select(n));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(n)}})}$('#scopeTitle').textContent=scope==='全部'?title:scope;$('#count').textContent=`${nodes.length} 個可見節點 · ${edges.length} 條有向邊 · 完整範圍 ${current.nodes.length} 節點`;fit()}
function applyZoom(){if(!current)return;$('#graph').setAttribute('width',current.W*zoom);$('#graph').setAttribute('height',current.H*zoom);$('#zoomText').textContent=Math.round(zoom*100)+'%'}
function fit(){if(!current)return;zoom=Math.min(1,Math.max(.2,($('#canvas').clientWidth-20)/current.W));applyZoom()}
function select(n){selected=n.id;const parents=current?current.edges.filter(e=>e[1]===n.id).map(e=>current.nodes.find(x=>x.id===e[0])).filter(Boolean):[];const children=current?current.edges.filter(e=>e[0]===n.id).map(e=>current.nodes.find(x=>x.id===e[1])).filter(Boolean):[];$('#detail').innerHTML=`<div class="pill">${['ROOT','DOMAIN','CONTEXT / CATEGORY','TERM'][n.level]}</div><strong>${esc(n.label)}</strong><p>${esc(D.notes[n.label]|| (n.level===3?'依研究問題與方法假設判斷適用性；相同方法可出現在多個分類或情境。':'沿箭頭查看下游分類或方法。'))}</p>`;for(const [label,ns]of [['上游',parents],['下游',children]]){if(!ns.length)continue;let div=document.createElement('div');div.append(label+'：');for(const item of ns){let b=document.createElement('button');b.textContent=item.label;b.onclick=()=>{if(item.level===3)locate(item.label);else{select(item);const el=[...document.querySelectorAll('g.node')].find(e=>e.dataset.id===item.id);el?.scrollIntoView({block:'center',inline:'center',behavior:'smooth'})}};div.append(b)}$('#detail').append(div)}if(n.level===3){const memberships=[...D.knowledge,...D.decision].filter(r=>r.terms.includes(n.label));const p=document.createElement('p');p.textContent='全部分類／情境：'+memberships.map(r=>r.domain+' › '+r.group).join('；');$('#detail').append(p)}document.querySelectorAll('g.node rect').forEach(e=>{let on=e.parentElement.dataset.id===n.id;e.setAttribute('stroke',on?'#cf953a':'#b8cdc1');e.setAttribute('stroke-width',on?3:1)})}
function locate(term){let r=D.knowledge.find(r=>r.terms.includes(term)),m='knowledge';if(!r){r=D.decision.find(r=>r.terms.includes(term));m='decision'}if(!r)return;mode=m;scope=r.domain;$('#depth').value='3';updateViews();categories();render();const n=current.nodes.find(n=>n.label===term);if(n){select(n);requestAnimationFrame(()=>{const el=[...document.querySelectorAll('g.node')].find(e=>e.dataset.id===n.id);el?.scrollIntoView({block:'center',inline:'center',behavior:'smooth'})})}}
function search(){const q=$('#search').value.trim().toLowerCase();const out=$('#searchResults');out.innerHTML='';if(!q)return;const hits=allTerms.filter(t=>t.toLowerCase().includes(q)||[...D.knowledge,...D.decision].some(r=>r.terms.includes(t)&&(r.domain+' '+r.group).toLowerCase().includes(q)));const info=document.createElement('small');info.textContent=`${hits.length} 個結果`;out.append(info);for(const t of hits){let b=document.createElement('button');b.textContent=t;b.onclick=()=>locate(t);out.append(b)}if(mode==='catalog')catalog()}
function catalog(){const q=$('#search').value.trim().toLowerCase();let html='<h2>完整內容清單</h2><p>點選術語可跳至 DAG。使用左側搜尋篩選清單。</p>';for(const [key,title]of [['knowledge','統計知識分類'],['decision','方法選用情境']]){let rs=D[key].filter(r=>(r.domain+' '+r.group+' '+r.terms.join(' ')).toLowerCase().includes(q));html+=`<h3>${title} · ${rs.length} 組</h3><table><thead><tr><th>主分類</th><th>次分類／情境</th><th>術語／方法</th></tr></thead><tbody>`;for(const r of rs)html+=`<tr><td>${esc(r.domain)}</td><td>${esc(r.group)}</td><td>${r.terms.map(t=>`<button class="catalog-term" data-term="${esc(t)}">${esc(t)}</button>`).join('； ')}</td></tr>`;html+='</tbody></table>'}$('#catalogView').innerHTML=html;$('#catalogView').querySelectorAll('[data-term]').forEach(b=>b.onclick=()=>locate(b.dataset.term))}
function updateViews(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#graphView').hidden=['catalog','about'].includes(mode);$('#catalogView').hidden=mode!=='catalog';$('#aboutView').hidden=mode!=='about'}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;scope=rows()[0].domain;$('#depth').value='3';updateViews();categories();render()});$('#depth').onchange=render;$('#search').oninput=()=>{search();if(!$('#search').value&&mode==='catalog')catalog()};$('#plus').onclick=()=>{zoom=Math.min(2.5,zoom*1.2);applyZoom()};$('#minus').onclick=()=>{zoom=Math.max(.1,zoom/1.2);applyZoom()};$('#fit').onclick=fit;$('#canvas').addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();zoom=Math.max(.1,Math.min(2.5,zoom*(e.deltaY<0?1.1:.9)));applyZoom()}},{passive:false});$('#export').onclick=()=>{const clone=$('#graph').cloneNode(true);clone.setAttribute('width',current.W);clone.setAttribute('height',current.H);const blob=new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml;charset=utf-8'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='statistics-dag.svg';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('#aboutView').innerHTML=`<h2>如何閱讀這份 DAG</h2><p>本圖整合原始 Statistics 清單、兩張分類圖片，以及對話中新增的方法選用架構。箭頭一律由主題指向次分類，再指向術語或方法。相同術語可有多個上游，形成有向無環圖；這不是因果 DAG。</p><h3>操作</h3><ol><li>選擇「知識分類」或「方法選用」，再選左側範圍。</li><li>「全部」預設顯示主分類；調整層級可顯示全部節點。</li><li>點選節點查看完整名稱、上游／下游與方法提醒。</li><li>搜尋中英文名稱；完整清單提供可搜尋的表格備援。</li><li>圖形可縮放並匯出 SVG；滑動視窗即可瀏覽大圖。</li></ol><h3>選用前的七項判斷</h3><p>分析目的 → 依變項數目 → 依變項尺度 → 自變項性質 → 樣本組數 → 獨立／配對／重複／群聚關係 → 分布、變異數、線性及期望次數等假設。圖中的並列方法是候選選項，並非彼此無條件替代。</p><h3>重要分類修正</h3><ul><li>Percentile 是位置指標；Central limit theorem 屬極限理論。</li><li>Nelson–Aalen 估計累積風險函數。</li><li>名義或序位資料也能使用參數模型，例如 logistic regression。</li><li>Multiple regression 可只有一個依變項；multivariate analysis 涉及多個結果或多變量結構。</li><li>相關、關聯、一致性與因果各有不同意義。</li><li>Natural experiment 歸入準實驗取向；是否支持因果推論仍須評估具體設計。</li></ul><h3>原圖與術語處理</h3><p>原圖的 Wilcoxon 分成 signed-rank 與 rank-sum；Cochran 的配對二元用途標成 Cochran’s Q。原圖將序列、趨勢與分布檢定混列者已重新歸類。未清楚定義的 Bootstrap（UV）、Tukey 快速檢定、Olmstead–Tukey、Hollander 與聯立係數／結合指數保留在待釐清區。圖片提到的 Moses、Wald–Wolfowitz、Cox–Stuart 等另列專門用途。未將模糊名稱自行猜定為另一項檢定。</p><p>英文全名與常見別名已合併：Pearson product-moment → Pearson correlation；maximum posterior → maximum a posteriori；product limit → Kaplan–Meier；nonparametric ANOVA 依獨立／相依設計拆分。原始圖片不隨公開專案重製。</p><h3>資料與維護</h3><p>data.js 是離線網頁直接載入的資料；data.json 是同內容的可交換版本。編輯 JSON 後可執行 python3 sync_data.py 同步。無追蹤、無外部字型、無 CDN。來源只支援特定修正，並非所有方法的完整使用手冊。</p><h3>參考來源</h3><ul>${D.sources.map(s=>`<li>${s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`:esc(s.title)}</li>`).join('')}</ul>`;
$('#totals').textContent=`${D.knowledge.length} 組分類 · ${D.decision.length} 個選用情境 · ${allTerms.length} 個術語`;
categories();render();catalog();window.addEventListener('resize',()=>{if(!['catalog','about'].includes(mode))fit()});
